// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_cycle6/test/features/home/data/repo/home_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:elevate_cycle6/config/base_response/base_response.dart' as _i5;
import 'package:elevate_cycle6/features/home/api/client/home_api_client.dart'
    as _i2;
import 'package:elevate_cycle6/features/home/api/datasource/local/home_local_datasource_impl.dart'
    as _i8;
import 'package:elevate_cycle6/features/home/api/datasource/remote/home_remote_datasource_impl.dart'
    as _i3;
import 'package:elevate_cycle6/features/home/data/models/product_dto.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHomeApiClient_0 extends _i1.SmartFake implements _i2.HomeApiClient {
  _FakeHomeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSourceImpl extends _i1.Mock
    implements _i3.HomeRemoteDataSourceImpl {
  MockHomeRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeApiClient get homeApiClient =>
      (super.noSuchMethod(
            Invocation.getter(#homeApiClient),
            returnValue: _FakeHomeApiClient_0(
              this,
              Invocation.getter(#homeApiClient),
            ),
          )
          as _i2.HomeApiClient);

  @override
  _i4.Future<List<String>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<_i5.BaseResponse<List<_i6.ProductDTO>>> getProducts({
    String? categoryId = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {#categoryId: categoryId}),
            returnValue:
                _i4.Future<_i5.BaseResponse<List<_i6.ProductDTO>>>.value(
                  _i7.dummyValue<_i5.BaseResponse<List<_i6.ProductDTO>>>(
                    this,
                    Invocation.method(#getProducts, [], {
                      #categoryId: categoryId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<List<_i6.ProductDTO>>>);
}

/// A class which mocks [HomeLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeLocalDataSourceImpl extends _i1.Mock
    implements _i8.HomeLocalDataSourceImpl {
  MockHomeLocalDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }
}
